### ISSUE TITLE
Claim error while using static qr claim 

### ISSUE THREAD

**Issue by arvee-init** [poap-xyz/poap-qr-kiosk#51]
Claim error: drop_id.includes is not a function (remote)

**Comment by arvee-init** [comment]
@actuallymentor Ran into this issue on thursday last week. Is this fixed with last weeks commit?

**Comment by actuallymentor** [comment]
Did you try to use a code that did not have an approved drop yet?

Is the error in the frontend?

**Comment by arvee-init** [comment]
Fixed.
